### ISSUE TITLE
При запуске собранной среды ошибка - не хватает javafx

### ISSUE THREAD

**Issue by TsSaltan** [jphp-group/develnext-ide#13]
![oracle open java runtime 8+ required with javafx](https://user-images.githubusercontent.com/3524731/62152046-59413000-b30a-11e9-908d-7403fc954b37.png)

**Comment by TsSaltan** [comment]
https://github.com/jphp-group/develnext-17/blob/master/dn-launcher/src-jvm/main/java/org/develnext/ide/Launcher.java#L58
https://github.com/jphp-group/develnext-17/blob/master/dn-launcher/src-jvm/main/java/org/develnext/ide/Launcher.java#L70

**Comment by MWGuy** [comment]
Этот код проверяет наличие JavaFX в рантайме, из за этого ошибка. Просто в новой сборки DN JFX в рантайм лаунчера не включается

**Comment by TsSaltan** [comment]
@MWGuy, мб эту проверку просто убрать, насколько она важна, если рядом со сборкой есть jre с нужной версией java и с компонентами

**Comment by MWGuy** [comment]
Я перепишу эту проверку. Она будет проверять нужную версию java 11+

**Comment by dim-s** [comment]
Эта проверка важна, т.к. не раз помогала диагностировать проблему у пользователей. Надо переделать под Java 11.
