### ISSUE TITLE
Error with Prepare IDE dependencies

### ISSUE THREAD

**Issue by zeko2010ss** [jphp-group/develnext-ide#2]
Hello I got this error and I do my best to find away but can't solve it
[WARNING] -> failed to install jphp-core@~1.0.0, cannot find package.
[WARNING] -> failed to install jphp-gui-ext@~1.0.0, cannot find package.
![Screenshot_14](https://user-images.githubusercontent.com/10324266/55676958-0bc63080-58df-11e9-89b1-f1abf2fb0ec4.png)

**Comment by MWGuy** [comment]
Install LTS distribution of java

**Comment by MWGuy** [comment]
This issue is not active. I just close it
